-- +goose Up
CREATE TABLE batch_reconciliation_summary (
	batch_contract_id                    UUID         PRIMARY KEY REFERENCES batch_contracts_core(batch_contract_id),
	tenant_id                            TEXT         NOT NULL,
	total_count                          INT          NOT NULL DEFAULT 0,
	success_count                        INT          NOT NULL DEFAULT 0,
	failed_count                         INT          NOT NULL DEFAULT 0,
	pending_count                        INT          NOT NULL DEFAULT 0,
	reversed_count                       INT          NOT NULL DEFAULT 0,
	partial_recon_count                  INT          NOT NULL DEFAULT 0,
	total_intended_amount_minor          NUMERIC(20,2) NOT NULL DEFAULT 0,
	total_confirmed_amount_minor         NUMERIC(20,2) NOT NULL DEFAULT 0,
	original_settled_amount_minor        NUMERIC(20,2) NOT NULL DEFAULT 0,
	total_variance_minor                 NUMERIC(20,2) NOT NULL DEFAULT 0,
	batch_finality_status                TEXT         NOT NULL DEFAULT 'PROCESSING',
	CHECK (batch_finality_status IN (
		'PROCESSING', 'FULLY_RECONCILED', 'PARTIALLY_RECONCILED',
		'FAILED', 'REQUIRES_REVIEW', 'CLOSED'
	)),
	total_intent_count                   INT          NOT NULL DEFAULT 0,
	matched_intent_count                 INT          NOT NULL DEFAULT 0,
	ambiguous_count                      INT          NOT NULL DEFAULT 0,
	unresolved_intent_count              INT          NOT NULL DEFAULT 0,
	conflicted_count                     INT          NOT NULL DEFAULT 0,
	orphan_observation_count             INT          NOT NULL DEFAULT 0,
	original_intended_amount_minor       NUMERIC(20,2) NOT NULL DEFAULT 0,
	ambiguous_amount_minor               NUMERIC(20,2) NOT NULL DEFAULT 0,
	unresolved_intended_amount_minor     NUMERIC(20,2) NOT NULL DEFAULT 0,
	conflicted_amount_minor              NUMERIC(20,2) NOT NULL DEFAULT 0,
	orphan_observed_amount_minor         NUMERIC(20,2) NOT NULL DEFAULT 0,
	net_batch_delta_minor                NUMERIC(20,2) NOT NULL DEFAULT 0,
	intent_count_coverage                NUMERIC(7,6)  NOT NULL DEFAULT 0,
	intent_value_coverage                NUMERIC(7,6)  NOT NULL DEFAULT 0,
	observed_count_allocation_coverage   NUMERIC(10,6) NOT NULL DEFAULT 0,
	intent_row_count                     INT          NOT NULL DEFAULT 0,
	intent_total_amount_minor            NUMERIC(20,2) NOT NULL DEFAULT 0,
	intent_amount_square_sum             NUMERIC(30,2) NOT NULL DEFAULT 0,
	intent_min_amount_minor              NUMERIC(20,2),
	intent_max_amount_minor              NUMERIC(20,2),
	client_payout_ref_present_count      INT          NOT NULL DEFAULT 0,
	batch_currency                       TEXT,
	batch_source_system                  TEXT,
	batch_rail                           TEXT,
	batch_intent_type                    TEXT,
	batch_provider_key                   TEXT,
	first_intent_created_at              TIMESTAMPTZ,
	under_settlement_amount_minor        NUMERIC(20,2) NOT NULL DEFAULT 0,
	predicted_leakage_rate               NUMERIC(10,6),
	predicted_leakage_minor              NUMERIC(20,2),
	predicted_leakage_model_id           TEXT,
	predicted_at                         TIMESTAMPTZ,
	currency                             CHAR(3)      NOT NULL DEFAULT 'INR',
	matched_intended_amount_minor        NUMERIC(20,2),
	total_observed_amount_minor          NUMERIC(20,2),
	matched_observed_amount_minor        NUMERIC(20,2),
	matched_pair_variance_minor          NUMERIC(20,2),
	observed_value_coverage              NUMERIC(7,6)  NOT NULL DEFAULT 0,
	matched_attachment_confidence        NUMERIC(6,5),
	matched_attachment_ambiguity         NUMERIC(6,5),
	source_service                       TEXT NOT NULL DEFAULT 'zord-outcome-engine',
	source_version                       TEXT NOT NULL DEFAULT 'legacy',
	source_payload_hash                  TEXT,
	computed_at                          TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- +goose Down
DROP TABLE batch_reconciliation_summary;
