/** Spec 7.6 - Intent Journal customer-facing copy. */

export const intentJournalCopy = {
  pageTitle: 'Intent Journal',
  pageSubtitle: 'Validate, govern, and seal payout instructions before dispatch.',
  hero: {
    label: 'Intended payment value',
    subtitle: 'Sum of payout obligations in this batch',
  },
  kpi: {
    intendedValue: 'Intended payment value',
    instructions: 'Instructions',
    readiness: 'Pre-dispatch readiness',
    readinessTooltip:
      'Share of instructions that are ready to seal, of all instructions in this batch (eligible ÷ total).',
    blockedValue: 'Blocked value',
    blockedValueHint: 'Pre-dispatch value held by policy - not confirmed fraud.',
    needsReview: 'Needs review',
  },
  tabs: {
    instructions: 'Instructions',
    reviewItems: 'Review queue',
  },
  table: {
    searchPlaceholder: 'Search intent, obligation, recipient, amount…',
    headers: {
      intentId: 'Intent ID',
      obligationRef: 'Obligation ref',
      recipient: 'Recipient',
      amount: 'Amount',
      policyStatus: 'Policy',
      sourceIntegrity: 'Source integrity',
      riskState: 'Risk',
      actionContract: 'Action Contract',
      lifecycle: 'Lifecycle',
    },
    emptyInstructions: 'No payout instructions in this batch yet.',
    emptyReview: 'No review items for this batch.',
  },
  lifecycle: {
    draft: 'Draft',
    needsReview: 'Needs review',
    readyToSeal: 'Ready to seal',
    sealed: 'Sealed',
    dispatched: 'Dispatched',
    blocked: 'Blocked',
  },
  changeSignal: {
    none: 'No material change',
    beneficiary: 'Beneficiary changed',
    amount: 'Amount changed',
    sourceVersion: 'Source version changed',
  },
  actions: {
    validate: 'Validate batch',
    applyPolicy: 'Apply policy',
    openReview: 'Open review queue',
    compareSource: 'Compare source',
    sealEligible: 'Seal eligible intents',
    openContract: 'Open Action Contract',
    export: 'Export',
  },
  sidebar: {
    batchLabel: 'Batch',
    instructions: 'instructions',
    intendedValue: 'intended value',
    selectBatch: 'Select a batch from the sidebar',
    readiness: 'Readiness',
    blocked: 'Blocked',
    mode: 'Mode',
  },
  health: {
    fileMapping: 'File Mapping Status',
    requiredFields: 'Required Field Health',
    duplicateRisk: 'Duplicate Risk',
    beneficiaryValidation: 'Beneficiary Validation',
    tokenization: 'Tokenization Status',
    notConnected: 'Not connected yet',
    awaitingData: 'Awaiting data from ingest profile',
  },
  export: {
    menuLabel: 'Export',
    intentReport: 'Export payment intent report',
    reviewItems: 'Export review items',
    dispatchReady: 'Export dispatch-ready file',
    auditSummary: 'Export audit summary',
    dispatchNotAvailable: 'Dispatch export not available yet',
    auditNotAvailable: 'Audit bundle not available yet',
  },
  seal: {
    success: (n: number) =>
      `Sealed ${n} eligible intent${n === 1 ? '' : 's'}. Source obligations were not overwritten.`,
    none: 'No eligible intents to seal. Blocked or incomplete source authority cannot be sealed.',
    blockedHint: 'Rows with missing source authority or active policy blocks cannot be sealed.',
  },
} as const
