import type {
  AmbiguityKpiResolved,
  AmbiguityVelocityPoint,
  AmbiguityVelocitySeries,
  IntelligenceBatchRow,
  MatchingExecutionHeatmap,
} from '@/services/payout-command/prod-api/intelligenceTypes'
import { formatAmbiguityInr } from './formatAmbiguityInr'

export type VelocityChartRow = {
  period: string
  review: number
  lowConf: number
  missing: number
}

export type TimeframeKey = 'day' | 'week' | 'month' | 'year'

const TF_UI_TO_API: Record<string, TimeframeKey> = {
  Day: 'day',
  Week: 'week',
  Month: 'month',
  Year: 'year',
}

export function uiTimeframeToApi(tf: string): TimeframeKey {
  return TF_UI_TO_API[tf] ?? 'month'
}

function normalizeVelocityPoint(p: AmbiguityVelocityPoint): VelocityChartRow {
  return {
    period: p.period,
    review: p.review_count ?? 0,
    lowConf: p.low_confidence_count ?? 0,
    missing: p.missing_ref_count ?? 0,
  }
}

export function getVelocitySeriesForTimeframe(
  amb: AmbiguityKpiResolved | null,
  tf: string,
): VelocityChartRow[] {
  const key = uiTimeframeToApi(tf)
  const series = amb?.velocity_series?.[key]
  if (!series?.length) return []
  return series.map(normalizeVelocityPoint)
}

export function formatDeltaPct(delta: number | undefined): string | null {
  if (delta == null || !Number.isFinite(delta)) return null
  const sign = delta > 0 ? '+' : ''
  return `${sign}${delta.toFixed(1)}%`
}

export function getKpiDeltas(amb: AmbiguityKpiResolved | null) {
  return {
    ambiguousIntents: formatDeltaPct(amb?.ambiguous_intent_count_delta_pct),
    ambiguityRate: formatDeltaPct(amb?.ambiguity_rate_delta_pct),
    missingRefRate: formatDeltaPct(amb?.provider_ref_missing_rate_delta_pct),
    valueAtRisk: formatDeltaPct(
      amb?.value_at_risk_delta_pct ?? amb?.value_at_risk_delta_pct_from_prior,
    ),
  }
}

export function getValueAtRiskDelta(amb: AmbiguityKpiResolved | null): string | null {
  const delta = amb?.value_at_risk_delta_pct ?? amb?.value_at_risk_delta_pct_from_prior
  return formatDeltaPct(delta)
}

export function getMatchingHeatmap(
  _amb: AmbiguityKpiResolved | null,
  heatmapOverride?: MatchingExecutionHeatmap | null,
): MatchingExecutionHeatmap | null {
  // Only the dedicated /ambiguity/heatmap API is the source of truth.
  // Never fall back to KPI-embedded heatmap — different poll cycle = stale cross-contamination.
  return heatmapOverride ?? null
}

export function getMatchingSummary(
  _amb: AmbiguityKpiResolved | null,
  heatmapOverride?: MatchingExecutionHeatmap | null,
): string | null {
  // Summary is generated by the dedicated heatmap mapper from live batch data.
  // KPI-response summary fields are excluded — different API, different snapshot.
  return heatmapOverride?.summary ?? null
}

// API field is match_confidence (0–100, pre-scaled by backend). match_confidence_pct is never sent.
export function batchMatchPctDisplay(b: IntelligenceBatchRow): string {
  const v = b.match_confidence
  if (v == null || String(v).trim() === '') return '—'
  const n = typeof v === 'number' ? v : Number(String(v).trim())
  if (Number.isFinite(n) && n === 0) return '0'
  return String(v).trim()
}

export function batchMatchPct(b: IntelligenceBatchRow): number | null {
  const v = b.match_confidence
  if (v != null && Number.isFinite(v)) return v
  return null
}

// Per-batch value at risk: unresolved_intended_amount_minor from /intelligence/batches response.
// value_at_risk_minor is tenant-level only (ambiguity KPI API) — not returned per batch row.
export function batchDisplayValue(b: IntelligenceBatchRow): string {
  const v = b.unresolved_intended_amount_minor
  if (v == null || String(v).trim() === '') return '—'
  const n = typeof v === 'number' ? v : Number(String(v).replace(/,/g, ''))
  if (Number.isFinite(n) && n === 0) return '0'
  return formatAmbiguityInr(v)
}
